/**
 * Musical styles offered as autocomplete suggestions on the artist form.
 *
 * Extracted from the alphabetical sections of
 * https://fr.wikipedia.org/wiki/Liste_de_styles_musicaux (717 entries,
 * CC BY-SA). Style names are largely proper nouns, so the same list serves both
 * languages. Used with a <datalist>, not a <select>: 717 options in a dropdown
 * would be unusable, and this keeps the field free-text so an artist can enter a
 * style the list does not cover.
 */
export const MUSIC_STYLES = [
  "2 tone",
  "2-step garage",
  "Acid blues",
  "Acid breaks",
  "Acid house",
  "Acid jazz",
  "Acid rock",
  "Acid techno",
  "Acid trance",
  "Acidcore",
  "Adult contemporary",
  "Afrobeat",
  "Afrobeats",
  "Afropop",
  "Afrotrap",
  "Aguinaldo",
  "Allaoui",
  "Amapiano",
  "Ambient",
  "Ambient house",
  "Ambient jungle",
  "Ambient techno",
  "Americana",
  "Anarcho-punk",
  "Anti-folk",
  "Apala",
  "Arena rock",
  "Ars antiqua",
  "Ars nova",
  "Ars subtilior",
  "Art punk",
  "Art rock",
  "Austropop",
  "Avant-funk",
  "Avant-garde jazz",
  "Avant-prog",
  "Avanthop",
  "Axé",
  "Bachata",
  "Bachatango",
  "Baggy",
  "Baguala",
  "Baião",
  "Baila",
  "Baile funk",
  "Bakersfield sound",
  "Balearic beat",
  "Balearic trance",
  "Ballade",
  "Ballet",
  "Baltimore club",
  "Bambuco",
  "Barbershop",
  "Bass music",
  "Bassline",
  "Batucada",
  "Bay Area thrash metal",
  "Beat",
  "Beatbox",
  "Bebop",
  "Beiguan",
  "Benga",
  "Berceuse",
  "Big band",
  "Big beat",
  "Big room house",
  "Biguine",
  "Bikutsi",
  "Black metal",
  "Black metal norvégien",
  "Black metal symphonique",
  "Bluegrass",
  "Blues",
  "Blues africain",
  "Blues électrique",
  "Blues rock",
  "Blues touareg",
  "Blues traditionnel",
  "Boléro",
  "Bongo Flava",
  "Boogaloo",
  "Boogie-woogie",
  "Bossa nova",
  "Bounce music",
  "braindance",
  "Brass band",
  "Breakbeat",
  "Breakbeat hardcore",
  "Breakcore",
  "Britpop",
  "Broken beat",
  "Brutal death metal",
  "Bubblegum dance",
  "Bubblegum pop",
  "C-pop",
  "C86",
  "Calypso",
  "Cantopop",
  "Cello rock",
  "Cha-cha-cha",
  "Chaâbi algérien",
  "Chaâbi marocain",
  "Changüí",
  "Chanson française",
  "Chant grégorien",
  "Chicago blues",
  "Chicago house",
  "Chill-out",
  "Chillstep",
  "Chillwave",
  "City pop",
  "Classic rag",
  "Cloud rap",
  "Cold wave",
  "College rock",
  "Combat folk",
  "Complainte",
  "Complextro",
  "Concerto",
  "Conte musical",
  "Contradanza",
  "Cool jazz",
  "Country",
  "Country alternative",
  "Country folk",
  "Country néo traditionnelle",
  "Country pop",
  "Country rap",
  "Country rock",
  "Country soul",
  "Coupé-décalé",
  "Cowpunk",
  "Crossover",
  "Crossover thrash",
  "Crunk",
  "Crunk'n'b",
  "Crunkcore",
  "Crust punk",
  "D-beat",
  "Dance",
  "Dance-pop",
  "Dance-punk",
  "Dance-rock",
  "Dancehall",
  "Dangdut",
  "Danzón",
  "Dark ambient",
  "Dark jazz",
  "Dark metal",
  "Dark psytrance",
  "Dark wave",
  "Dark wave néo-classique",
  "Darkstep",
  "Death 'n' roll",
  "Death metal",
  "Death metal mélodique",
  "Death metal technique",
  "Death rock",
  "Death-doom",
  "Deathcore",
  "Deathcountry",
  "Deathgrind",
  "Deep house",
  "Deepkho",
  "Delta blues",
  "Detroit blues",
  "Digital hardcore",
  "Dirty South",
  "Disco",
  "Disco house",
  "Disco polo",
  "Diva house",
  "Dixieland",
  "Djent",
  "Doo-wop",
  "Doom metal",
  "Downtempo",
  "Dream pop",
  "Dream trance",
  "Drill",
  "Drill and bass",
  "Drone",
  "Drum and bass",
  "Drumfunk",
  "Drumstep",
  "Dub",
  "Dub poetry",
  "Dub techno",
  "Dubstep",
  "Dubstyle",
  "Dunedin sound",
  "Dungeon synth",
  "Dutch house",
  "Early hardcore",
  "Early reggae",
  "Easycore",
  "Electro house",
  "Electro swing",
  "Électro-industriel",
  "Electroclash",
  "Electronica",
  "Electronicore",
  "Electronique",
  "Electrotango",
  "Emo",
  "Emo pop",
  "Éthio-jazz",
  "Ethno-jazz",
  "Euro disco",
  "Eurobeat",
  "Eurodance",
  "Europop",
  "Extratone",
  "Fado",
  "Fanfare",
  "Fidget house",
  "Filin",
  "Flamenco",
  "Folk",
  "Folk metal",
  "Folk progressif",
  "Folk psychédélique",
  "Folk rock",
  "Folktronica",
  "Freakbeat",
  "Free jazz",
  "Freeform hardcore",
  "Freestyle",
  "French touch",
  "Frenchcore",
  "Fun-punk",
  "Funk",
  "Funk metal",
  "Funk rock",
  "Funktronica",
  "Funky house",
  "Future bass",
  "Future garage",
  "Future house",
  "G-funk",
  "Gabber",
  "Gaelic punk",
  "Gangsta rap",
  "Garage house",
  "Garage punk",
  "Garage rock",
  "Geek rock",
  "Ghetto house",
  "Ghettotech",
  "Gims Beat",
  "Glam metal",
  "Glam punk",
  "Glam rock",
  "Glitch",
  "Glitch-hop",
  "Goregrind",
  "Gospel",
  "Gospel blues",
  "Gothabilly",
  "Gqom",
  "Grebo",
  "Grime",
  "Grindcore",
  "Grindie",
  "Groove metal",
  "Grunge",
  "Guajira",
  "Guaracha",
  "Gypsy punk",
  "Handsup",
  "Happy gabber",
  "Happy hardcore",
  "Hard bop",
  "Hard house",
  "Hard rock",
  "Hard trance",
  "Hardbag",
  "Hardbass",
  "Hardcore chrétien",
  "Hardcore mélodique",
  "Hardstep",
  "Hardstyle",
  "Hardtechno",
  "Harsh noise",
  "Heartland rock",
  "Heavy metal",
  "Heavy metal traditionnel",
  "Hi-NRG",
  "Highlife",
  "Hip-hop",
  "Hip-hop alternatif",
  "Hip-hop australien",
  "Hip-hop chrétien",
  "Hip-hop expérimental",
  "Hip-hop old-school",
  "Hip-hop psychédélique",
  "Hip-hop sud-coréen",
  "Hip-house",
  "Hiplife",
  "Hipster-hop",
  "Honky tonk",
  "Honkyoku",
  "Horror punk",
  "Horrorcore",
  "House music",
  "House progressive",
  "Hybrid trap",
  "Illbient",
  "Indie dance",
  "Indie folk",
  "Industrial hardcore",
  "Italo dance",
  "Italo disco",
  "Italo house",
  "J-core",
  "J-pop",
  "J-rock",
  "Jangle pop",
  "Jazz",
  "Jazz afro-cubain",
  "Jazz blues",
  "Jazz manouche",
  "Jazz modal",
  "Jazz Nouvelle-Orléans",
  "Jazz punk",
  "Jazz rap",
  "Jazz vocal",
  "Jazz West Coast",
  "Jazz-funk",
  "Jazzstep",
  "Jiuta",
  "Jump blues",
  "Jump-up",
  "Jumpstyle",
  "Jungle",
  "K-pop",
  "Kaneka",
  "Kansas City blues",
  "Kasékò",
  "Kawaii metal",
  "Kizomba",
  "Klezmer",
  "Kompa",
  "Krautrock",
  "Kuduro",
  "Kwaito",
  "Latin house",
  "Latin jazz",
  "Latin metal",
  "Lento violento",
  "Léròl",
  "Liquid funk",
  "Livetronica",
  "Lo-fi",
  "Logobi",
  "Louisiana blues",
  "Lounge",
  "Luk thung",
  "Madchester",
  "Mainstream hardcore",
  "Mainstream jazz",
  "Makina",
  "Makossa",
  "Maloya",
  "Mambo",
  "Mandopop",
  "Mangue beat",
  "Marche",
  "Mashup",
  "Math rock",
  "Mathcore",
  "Mbalax",
  "Medieval rock",
  "Memphis blues",
  "Merengue",
  "Merenhouse",
  "Metal alternatif",
  "Metal avant-gardiste",
  "Metal celtique",
  "Metal chrétien",
  "Metal extrême",
  "Metal gothique",
  "Metal industriel",
  "Metal néo-classique",
  "Metal oriental",
  "Metal progressif",
  "Metal symphonique",
  "Metalcore",
  "Metalcore mélodique",
  "Mgodro",
  "Miami bass",
  "Microhouse",
  "Midwest rap",
  "Milonga",
  "Min'yō",
  "Minneapolis sound",
  "Moombahcore",
  "Moombahton",
  "Mozambique",
  "Murga",
  "Musette",
  "Musique acadienne",
  "Musique acoustique",
  "Musique aléatoire",
  "Musique alternative",
  "Musique ancienne",
  "Musique arabo-andalouse",
  "Musique baroque",
  "Musique bretonne",
  "Musique celtique",
  "Musique classique",
  "Musique cubaine",
  "Musique de jeu vidéo",
  "Musique de variétés",
  "Musique électroacoustique",
  "Musique électronique",
  "Musique émergente",
  "Musique expérimentale",
  "Musique gothique",
  "Musique industrielle",
  "Musique instrumentale",
  "Musique irlandaise",
  "Musique japonaise",
  "Musique latine",
  "Musique LGBT",
  "Musique minimaliste",
  "Musique mixte",
  "Musique post-industrielle",
  "Musique progressive",
  "Musique romantique",
  "Musique sérielle",
  "Musique spectrale",
  "Musiques du monde",
  "Nardcore",
  "Nashville sound",
  "Nazi punk",
  "Nederpop",
  "Negro spiritual",
  "Neo soul",
  "Néo-bop",
  "Néo-classicisme",
  "Neo-psychedelia",
  "Néo-trad",
  "Néofolk",
  "Nerdcore",
  "Neue Deutsche Härte",
  "Neue Deutsche Welle",
  "Neurofunk",
  "New age",
  "New beat",
  "New jack swing",
  "New prog",
  "New wave",
  "New York blues",
  "New York hardcore",
  "Nightcore",
  "Nintendocore",
  "No wave",
  "Nocturne",
  "Noise pop",
  "Noise rock",
  "Northern soul",
  "Nouveau flamenco",
  "Nu gaze",
  "Nu jazz",
  "Nu metal",
  "Nu-disco",
  "Nu-NRG",
  "Nueva canción",
  "Nueva trova",
  "Oi!",
  "Old-time",
  "Opéra",
  "Opéra-rock",
  "Oratorio",
  "Outlaw country",
  "Pachanga",
  "Paisley Underground",
  "Palm-wine music",
  "Paso doble",
  "Philadelphia soul",
  "Phonk",
  "Piano blues",
  "Piano rock",
  "Piano stride",
  "Piedmont blues",
  "Pirate metal",
  "Polonaise",
  "Pop",
  "Pop alternative",
  "Pop baroque",
  "Pop indépendante",
  "Pop latino",
  "Pop metal",
  "Pop progressive",
  "Pop psychédélique",
  "Pop punk",
  "Pop rock",
  "Pop-rap",
  "Pornogrind",
  "Post-bop",
  "Post-disco",
  "Post-grunge",
  "Post-hardcore",
  "Post-metal",
  "Post-punk",
  "Post-rock",
  "Power ballad",
  "Power metal",
  "Power pop",
  "Powerviolence",
  "Prélude",
  "Progressive psytrance",
  "Protopunk",
  "Psychobilly",
  "Pub rock",
  "Punk blues",
  "Punk celtique",
  "Punk chrétien",
  "Punk folk",
  "Punk rock",
  "Punta rock",
  "Punto guajiro",
  "Queercore",
  "Quiet storm",
  "Rabiz",
  "Raga rock",
  "Ragga",
  "Ragtime",
  "Raï",
  "Raï'n'B",
  "Rap",
  "Rap East Coast",
  "Rap hardcore",
  "Rap metal",
  "Rap politique",
  "Rap rock",
  "Rap West Coast",
  "Rapcore",
  "Rave",
  "Rawstyle",
  "Rebetiko",
  "Red dirt",
  "Reggada",
  "Reggae",
  "Reggae fusion",
  "Reggaeton",
  "Rhapsodie",
  "Rhythm and blues",
  "Riot grrrl",
  "RnB alternatif",
  "RnB contemporain",
  "Rock",
  "Rock 'n' roll",
  "Rock alternatif",
  "Rock alternatif latino",
  "Rock argentin",
  "Rock brésilien",
  "Rock canadien",
  "Rock celtique",
  "Rock chilien",
  "Rock chinois",
  "Rock chrétien",
  "Rock communiste",
  "Rock électronique",
  "Rock en espagnol",
  "Rock expérimental",
  "Rock gothique",
  "Rock in opposition",
  "Rock indépendant",
  "Rock industriel",
  "Rock instrumental",
  "Rock néo-progressif",
  "Rock progressif",
  "Rock progressif espagnol",
  "Rock progressif français",
  "Rock progressif italien",
  "Rock psychédélique",
  "Rock sudiste",
  "Rock suédois",
  "Rock symphonique",
  "Rock turc",
  "Rock wagnérien",
  "Rockabilly",
  "Rocksteady",
  "Rondo",
  "Roots rock",
  "Rumba",
  "Rumba catalane",
  "Rumba congolaise",
  "Rumba flamenca",
  "Sadcore",
  "Saint Louis blues",
  "Salegy",
  "Salsa",
  "Salsa-ragga",
  "Salsaton",
  "Samba",
  "Samba funk",
  "Samba jazz",
  "Samba rock",
  "Samba-canção",
  "Samba-reggae",
  "Sambalanço",
  "Sambass",
  "Sankyoku",
  "Scherzo",
  "Schlager",
  "Schranz",
  "Screamo",
  "Séga",
  "Seggae",
  "Semba",
  "Shatta",
  "Shibuya-kei",
  "Shock rock",
  "Shoegazing",
  "Ska",
  "Ska punk",
  "Ska-jazz",
  "Skacore",
  "Skate punk",
  "Skiffle",
  "Slam",
  "Slow",
  "Slowcore",
  "Sludge metal",
  "Smooth jazz",
  "Snap",
  "Soca",
  "Soft rock",
  "Son cubain",
  "Sonate",
  "Songo",
  "Sophisti-pop",
  "Soukous",
  "Soul",
  "Soul blues",
  "Soul jazz",
  "Soul progressive",
  "Soul psychédélique",
  "Southern gospel",
  "Southern soul",
  "Space age pop",
  "Space rock",
  "Speed garage",
  "Speed metal",
  "Speedcore",
  "Splittercore",
  "Stoner rock",
  "Street punk",
  "Sunshine pop",
  "Surf",
  "Swamp blues",
  "Swamp pop",
  "Swing",
  "Symphonie",
  "Synthwave",
  "T-pop",
  "Tango",
  "Tango nuevo",
  "Taqwacore",
  "Tarentelle",
  "Tech house",
  "Tech trance",
  "Techno",
  "Techno de Détroit",
  "Techno hardcore",
  "Techno minimale",
  "Techstep",
  "Tecno rumba",
  "Tecno-brega",
  "Teen pop",
  "Terrorcore",
  "Texas blues",
  "Thrash metal",
  "Thrash metal allemand",
  "Thrashcore",
  "Timba",
  "Toccata",
  "Trallpunk",
  "Trance",
  "Trance Goa",
  "Trance psychédélique",
  "Trance vocale",
  "Trap",
  "Tribal house",
  "Tribe",
  "Trip hop",
  "Tropical house",
  "Tropipop",
  "Tumba francesa",
  "Twee pop",
  "UK garage",
  "UK hardcore",
  "Unblack metal",
  "Uplifting trance",
  "uptempo",
  "Vaporwave",
  "Viking metal",
  "Visual kei",
  "Vocal house",
  "West Coast blues",
  "Western Swing",
  "Witch house",
  "Wizard rock",
  "Wonky",
  "Wonky pop",
  "World music",
  "Yéla",
  "Yéyé",
  "Youth crew",
  "Zeuhl",
  "Ziglibithy",
  "Zouglou",
  "Zouk",
  "Zumba",
] as const;
